
const EXPORT_WIDTH=1200,EXPORT_HEIGHT=1700;
const state={activeTemplate:'profile',question:{firstCharacter:'',featureRequest:'',reasonStarted:'',messageToOps:'',freeSpace:''},profile:{name:'',xId:'',zetaHistory:'',creatorId:'',nickname:'',favoriteThing:'',profileImage:'',oshi1Name:'',oshi2Name:'',oshi3Name:'',oshi1Desc:'',oshi2Desc:'',oshi3Desc:'',oshi1Image:'',oshi2Image:'',oshi3Image:''}};
const DISABLE_PERSIST=Boolean(window.ZETA_DISABLE_PERSIST);
const tabs=document.querySelectorAll('.tab'),questionForm=document.getElementById('question-form'),profileForm=document.getElementById('profile-form'),previewCanvas=document.getElementById('preview-canvas'),previewSizeLabel=document.getElementById('preview-size-label'),downloadBtn=document.getElementById('download-btn'),iosBtn=document.getElementById('ios-btn'),resetBtn=document.getElementById('reset-btn'),iosSaveArea=document.getElementById('ios-save-area'),iosSaveImage=document.getElementById('ios-save-image');
const imageCache=new Map();
const qs=(s,r=document)=>r.querySelector(s);
function persist(){if(DISABLE_PERSIST)return;localStorage.setItem('zeta-cards-custom',JSON.stringify(state))}
function loadState(){if(DISABLE_PERSIST)return;const raw=localStorage.getItem('zeta-cards-custom');if(!raw)return;try{const saved=JSON.parse(raw);Object.assign(state.question,saved.question||{});Object.assign(state.profile,saved.profile||{});state.activeTemplate=saved.activeTemplate||'profile'}catch(e){console.warn(e)}}
function applyPresetFromWindow(){const preset=window.ZETA_PRESET;if(!preset)return;Object.assign(state.question,preset.question||{});Object.assign(state.profile,preset.profile||{});if(preset.activeTemplate)state.activeTemplate=preset.activeTemplate}
function fillForms(){Object.entries(state.question).forEach(([k,v])=>{const el=questionForm.elements.namedItem(k);if(el)el.value=v});Object.entries(state.profile).forEach(([k,v])=>{const el=profileForm.elements.namedItem(k);if(el&&el.type!=='file')el.value=v})}
function setTemplate(t){state.activeTemplate=t;tabs.forEach(tab=>{const a=tab.dataset.template===t;tab.classList.toggle('is-active',a);tab.setAttribute('aria-selected',String(a))});questionForm.classList.toggle('hidden',t!=='question');profileForm.classList.toggle('hidden',t!=='profile');persist();renderPreview()}
tabs.forEach(tab=>tab.addEventListener('click',()=>setTemplate(tab.dataset.template)));
questionForm.addEventListener('input',e=>{const {name,value}=e.target;state.question[name]=value;persist();renderPreview()});
profileForm.addEventListener('input',async e=>{const {name,value,type,files}=e.target;if(type==='file'){const file=files?.[0];if(!file)return;state.profile[name]=await readFileAsDataURL(file);imageCache.delete(state.profile[name]);persist();renderPreview();return}state.profile[name]=value;persist();renderPreview()});
resetBtn.addEventListener('click',()=>{if(!confirm('入力内容を消しますか？'))return;localStorage.removeItem('zeta-cards-custom');window.location.reload()});
downloadBtn.addEventListener('click',async()=>{try{const canvas=await buildExportCanvas();await saveCanvas(canvas,`zeta-card-${state.activeTemplate}.png`)}catch(e){console.error(e);alert('保存に失敗しました。')}})
iosBtn.addEventListener('click',async()=>{try{const canvas=await buildExportCanvas();iosSaveImage.src=canvas.toDataURL('image/png');iosSaveArea.classList.remove('hidden');iosSaveArea.scrollIntoView({behavior:'smooth',block:'start'})}catch(e){console.error(e);alert('PNG化に失敗しました。')}})
window.addEventListener('resize',renderPreview);
function readFileAsDataURL(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
function isIOS(){return /iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)}
function canvasToBlob(canvas){return new Promise(res=>canvas.toBlob(b=>res(b),'image/png'))}
async function saveCanvas(canvas,filename){const blob=await canvasToBlob(canvas);if(!blob)throw new Error('PNG化に失敗');const file=new File([blob],filename,{type:'image/png'});if(isIOS()&&navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:filename});return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function createCanvas(w=EXPORT_WIDTH,h=EXPORT_HEIGHT){const c=document.createElement('canvas');c.width=w;c.height=h;return c}
async function loadImage(src){
if(!src)return null;
if(imageCache.has(src))return imageCache.get(src);
const p=new Promise(res=>{
const i=new Image();
if(!String(src).startsWith('data:'))i.crossOrigin='anonymous';
i.onload=()=>res(i);
i.onerror=()=>{console.warn('image load failed',src);res(null)};
i.src=src
});
imageCache.set(src,p);
return p
}
function roundRect(ctx,x,y,w,h,r,fill=true,stroke=false){const rr=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+rr,y);ctx.arcTo(x+w,y,x+w,y+h,rr);ctx.arcTo(x+w,y+h,x,y+h,rr);ctx.arcTo(x,y+h,x,y,rr);ctx.arcTo(x,y,x+w,y,rr);ctx.closePath();if(fill)ctx.fill();if(stroke)ctx.stroke()}
function drawImageCover(ctx,img,x,y,w,h,r=0){if(!img)return;const imgRatio=img.width/img.height,boxRatio=w/h;let sx,sy,sw,sh;if(imgRatio>boxRatio){sh=img.height;sw=sh*boxRatio;sx=(img.width-sw)/2;sy=0}else{sw=img.width;sh=sw/boxRatio;sx=0;sy=(img.height-sh)/2}ctx.save();if(r>0){roundRect(ctx,x,y,w,h,r,false,false);ctx.clip()}ctx.drawImage(img,sx,sy,sw,sh,x,y,w,h);ctx.restore()}
function wrapText(ctx,text,maxWidth){const raw=String(text).split('\n'),lines=[];raw.forEach(line=>{if(!line){lines.push('');return}let buf='';for(const ch of line){const test=buf+ch;if(ctx.measureText(test).width>maxWidth&&buf){lines.push(buf);buf=ch}else buf=test}if(buf)lines.push(buf)});return lines}
function drawContainedText(ctx,text,box,opt={}){const o={maxFontSize:38,minFontSize:18,fontWeight:700,color:'#23233a',lineHeight:1.35,align:'left',valign:'top',paddingX:0,paddingY:0,...opt},content=String(text||'').trim();if(!content)return;let fs=o.maxFontSize,lines=[];while(fs>=o.minFontSize){ctx.font=`${o.fontWeight} ${fs}px system-ui,-apple-system,sans-serif`;lines=wrapText(ctx,content,Math.max(1,box.w-o.paddingX*2));const h=lines.length*fs*o.lineHeight;if(h<=Math.max(1,box.h-o.paddingY*2))break;fs--}ctx.font=`${o.fontWeight} ${fs}px system-ui,-apple-system,sans-serif`;ctx.fillStyle=o.color;ctx.textAlign=o.align;ctx.textBaseline='top';const total=lines.length*fs*o.lineHeight;let startY=box.y+o.paddingY;if(o.valign==='middle')startY=box.y+(box.h-total)/2;if(o.valign==='bottom')startY=box.y+box.h-total-o.paddingY;let x=box.x+o.paddingX;if(o.align==='center')x=box.x+box.w/2;if(o.align==='right')x=box.x+box.w-o.paddingX;lines.forEach((line,i)=>ctx.fillText(line,x,startY+i*fs*o.lineHeight))}
function drawSectionCard(ctx,x,y,w,h,title,body,opt={}){ctx.save();ctx.fillStyle=opt.fill||'#fff';ctx.strokeStyle=opt.stroke||'#d9d2ff';ctx.lineWidth=opt.lineWidth||3;roundRect(ctx,x,y,w,h,opt.radius||24,true,true);if(title){ctx.fillStyle=opt.titleBg||'#efeafd';roundRect(ctx,x+18,y-18,Math.min(w-36,360),48,18,true,false);ctx.fillStyle=opt.titleColor||'#5a4bb8';ctx.font='700 26px system-ui,-apple-system,sans-serif';ctx.textBaseline='middle';ctx.textAlign='left';ctx.fillText(title,x+34,y+6)}drawContainedText(ctx,body,{x:x+24,y:y+34,w:w-48,h:h-48},{maxFontSize:opt.maxFontSize||34,minFontSize:opt.minFontSize||18,lineHeight:opt.lineHeight||1.45});ctx.restore()}
function drawLabeledField(ctx,x,y,w,h,label,value){ctx.save();ctx.fillStyle='#fff';ctx.strokeStyle='#ddd4ff';ctx.lineWidth=3;roundRect(ctx,x,y,w,h,22,true,true);ctx.fillStyle='#efeafd';roundRect(ctx,x+16,y+14,220,34,17,true,false);ctx.fillStyle='#5a4bb8';ctx.font='700 22px system-ui,-apple-system,sans-serif';ctx.textBaseline='middle';ctx.fillText(label,x+30,y+31);drawContainedText(ctx,value,{x:x+248,y:y+14,w:w-272,h:h-20},{maxFontSize:46,minFontSize:24,valign:'middle'});ctx.restore()}
function drawBubbleField(ctx,x,y,w,h,label,value){ctx.save();ctx.fillStyle='#fff7ff';ctx.strokeStyle='#e3d8ff';ctx.lineWidth=3;roundRect(ctx,x,y,w,h,28,true,true);ctx.fillStyle='#a57ef4';ctx.font='700 20px system-ui,-apple-system,sans-serif';ctx.textBaseline='top';ctx.fillText(label,x+24,y+18);drawContainedText(ctx,value,{x:x+22,y:y+42,w:w-44,h:h-54},{maxFontSize:32,minFontSize:18,align:'center',valign:'middle'});ctx.restore()}
async function drawOshiCard(ctx,{index,x,y,w,h}){const img=await loadImage(state.profile[`oshi${index}Image`]),name=state.profile[`oshi${index}Name`],desc=state.profile[`oshi${index}Desc`];ctx.save();ctx.fillStyle='#fff';ctx.strokeStyle='#ddd4ff';ctx.lineWidth=3;roundRect(ctx,x,y,w,h,28,true,true);const imageHeight=238;ctx.fillStyle='#f3efff';roundRect(ctx,x+18,y+18,w-36,imageHeight,22,true,false);drawImageCover(ctx,img,x+18,y+18,w-36,imageHeight,22);ctx.fillStyle='#efeafd';roundRect(ctx,x+24,y+274,w-48,52,18,true,false);drawContainedText(ctx,name,{x:x+26,y:y+278,w:w-52,h:44},{maxFontSize:28,minFontSize:16,align:'center',valign:'middle',color:'#5a4bb8'});drawContainedText(ctx,desc,{x:x+22,y:y+344,w:w-44,h:h-366},{maxFontSize:24,minFontSize:15,lineHeight:1.5});ctx.restore()}
async function renderProfileCard(ctx,w,h){ctx.fillStyle='#f7f4ff';ctx.fillRect(0,0,w,h);const pad=48;ctx.fillStyle='#fff';ctx.strokeStyle='#ddd4ff';ctx.lineWidth=4;roundRect(ctx,pad,pad,w-pad*2,h-pad*2,42,true,true);ctx.fillStyle='#efeafd';roundRect(ctx,pad+24,pad+24,w-96,120,30,true,false);ctx.fillStyle='#5a4bb8';ctx.font='700 54px system-ui,-apple-system,sans-serif';ctx.textBaseline='middle';ctx.fillText('zeta 自己紹介カード',pad+48,pad+84);const pr={x:94,y:230,w:270,h:320};ctx.fillStyle='#f3efff';roundRect(ctx,pr.x,pr.y,pr.w,pr.h,24,true,false);drawImageCover(ctx,await loadImage(state.profile.profileImage),pr.x,pr.y,pr.w,pr.h,24);drawLabeledField(ctx,450,232,650,88,'なまえ',state.profile.name);drawLabeledField(ctx,450,334,650,88,'X ID',state.profile.xId);drawLabeledField(ctx,450,436,650,88,'zeta歴',state.profile.zetaHistory);drawLabeledField(ctx,450,538,650,88,'クリエイターID',state.profile.creatorId);drawBubbleField(ctx,84,646,454,110,'「○○って呼んでね」',state.profile.nickname);drawBubbleField(ctx,572,646,544,110,'好きなものは ○○ だよ♡',state.profile.favoriteThing);for(const card of [{index:1,x:84,y:778,w:316,h:778},{index:2,x:442,y:778,w:316,h:778},{index:3,x:800,y:778,w:316,h:778}])await drawOshiCard(ctx,card)}
async function renderQuestionCard(ctx,w,h){ctx.fillStyle='#f7f4ff';ctx.fillRect(0,0,w,h);const pad=48;ctx.fillStyle='#fff';ctx.strokeStyle='#ddd4ff';ctx.lineWidth=4;roundRect(ctx,pad,pad,w-pad*2,h-pad*2,42,true,true);ctx.fillStyle='#efeafd';roundRect(ctx,pad+24,pad+24,w-96,120,30,true,false);ctx.fillStyle='#5a4bb8';ctx.font='700 54px system-ui,-apple-system,sans-serif';ctx.textBaseline='middle';ctx.fillText('zeta 質問カード',pad+48,pad+84);drawSectionCard(ctx,84,220,470,220,'初めて話したキャラは？',state.question.firstCharacter,{maxFontSize:38});drawSectionCard(ctx,84,482,470,300,'zetaに欲しい新機能は？',state.question.featureRequest,{maxFontSize:32});drawSectionCard(ctx,602,220,514,260,'zetaを始めたきっかけ',state.question.reasonStarted,{maxFontSize:32});drawSectionCard(ctx,602,522,514,260,'運営に一言🥺',state.question.messageToOps,{maxFontSize:32});drawSectionCard(ctx,84,850,1032,702,'FREE SPACE',state.question.freeSpace,{maxFontSize:34,minFontSize:16,lineHeight:1.5})}
async function renderCard(ctx,w,h){ctx.clearRect(0,0,w,h);if(state.activeTemplate==='profile')await renderProfileCard(ctx,w,h);else await renderQuestionCard(ctx,w,h)}
async function buildExportCanvas(){const c=createCanvas(EXPORT_WIDTH,EXPORT_HEIGHT);await renderCard(c.getContext('2d'),EXPORT_WIDTH,EXPORT_HEIGHT);return c}
async function renderPreview(){previewSizeLabel.textContent=`出力 ${EXPORT_WIDTH} × ${EXPORT_HEIGHT}`;try{await renderCard(previewCanvas.getContext('2d'),previewCanvas.width,previewCanvas.height)}catch(e){console.error(e)}}
loadState();applyPresetFromWindow();fillForms();setTemplate(state.activeTemplate);renderPreview();
